### ISSUE TITLE
HAMi SANDBOX PROJECT ONBOARDING task list

### ISSUE THREAD

**Issue by wawa0210** [Project-HAMi/HAMi#476]
🔥🔥🔥 Congratulations! Thanks to the efforts of all the friends in the HAMi community, HAMi has successfully entered the sandbox project.   --> https://github.com/cncf/sandbox/issues/132

This task describes the task list to be completed for HAMi SANDBOX PROJECT ONBOARDING

### Here is a clear to-do list
 * [x]  Transfer [your domain to the CNCF](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63). The "LF Stakeholder email" is [projects@cncf.io](mailto:projects@cncf.io). @archlitchi 
 * [x]  Transfer any [trademark and logo assets to the Linux Foundation] (https://github.com/cncf/foundation/tree/main/agreements). @archlitchi 
 * [x]  Submit a [pull request](https://github.com/cncf/artwork) with your artwork. @archlitchi 
 * [x]  Transfer website analytics to [projects@cncf.io](mailto:projects@cncf.io). CNCF staff can help.  @archlitchi 
 * [ ]  Migrate your Slack channels (if any) to the [Kubernetes or CNCF Slack workspace] @wawa0210 

### A series of issues that arise

 * [ ] 🔥🔥🔥🔥🔥 License Compliance scan and repair, currently found several issues affecting CI  [details](https://app.fossa.com/projects/git%2Bgithub.com%2FProject-HAMi%2FHAMi/refs/branch/master/a12d62a4a2f159b22345783fedc6531dde6b2c3d) @william-wang 
 * [ ] project-hami https support @ouyangluwei163 

 --- 

 * [ ] The roadmap needs regular maintenance, and there is a dedicated markdown maintenance update
 * [ ] Version release standardization refers to semverV2 (covering main, minor, patch) three different versions @william-wang 
     * [ ] Standard, transparent and operable markdown guidelines
     * [ ] Covers all releases, images, charts, source code, etc.
     * [ ] release-notes also need
     * [x] Multi-architecture support (amd64 & arm64) @archlitchi 
 * [ ] Best practices improvement, currently only 28% [details](https://www.bestpractices.dev/en/projects/9416)
 * [ ] Need e2e testing, the first meaningful one
 * [x] Add issue templates
 * [ ] Community meetings need to record meeting minutes, screen recording, and upload to the public
     * [x] bilibili
     * [ ] youtube
     * [ ] dockerhub
     * [ ] twitter
   
### Some things need to be followed up, the owner is cncf staff @wawa0210 

 * [x]  Add the project to [DevStats](https://devstats.cncf.io/).
 * [x]  Add the project to [CLOmonitor](https://clomonitor.io/).
 * [ ]  Add the project to [LFX Insights](https://insights.lfx.linuxfoundation.org/). This is done by adding a read-only app to your GitHub organization once it's in CNCF GHE.
 * [x]  Add the project to [LFX Project Control Center](https://projectadmin.lfx.linuxfoundation.org/project/a0941000002wBz4AAE).
 * [ ]  Add a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/).
 * [x]  Invite developers to the [#maintainers-circle](https://app.slack.com/client/T08PSQ7BQ/C014YQ8CDCG) Slack channel.
 * [ ]  Send a welcome email to confirm maintainer list access.

**Comment by archlitchi** [comment]
Update: Transfer [your domain to the CNCF](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63). The "LF Stakeholder email" is [projects@cncf.io](mailto:projects@cncf.io). In transfer progress

Submit a [pull request](https://github.com/cncf/artwork) with your artwork. done

**Comment by wawa0210** [comment]
Update:

about Add a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/).

after ignore these rules，all check are passed
![image](https://github.com/user-attachments/assets/0e58dacc-0631-4c61-86da-e1696201243c)
Not sure if the ignore rule is correct

**Comment by Rei1010** [comment]
@wawa0210 i want to work on the e2e part
