### ISSUE TITLE
HAMi  Incubation PROJECT ONBOARDING prepare task list

### ISSUE THREAD

**Issue by wawa0210** [Project-HAMi/HAMi#751]
ref https://github.com/Project-HAMi/HAMi/issues/476

Here is a clear to-do list

**Community Governance**
- [ ] Clear community governance & contributor promotion channels @wawa0210 
- [ ] HAMi clear and continuously updated roadmap @archlitchi 

**Open security ssf**
- [ ] Vulnerability Reporting Process @william-wang 

Some things need to be followed up, the owner is cncf staff

**Comment by archlitchi** [comment]
**Community Governance**
- [ ] Adopters
- [ ] RoadMap
